dist: xenial
os: 
  - linux-ppc64le
sudo: required
language: node_js
node_js:
  - "7"

before_install:
  - sudo apt-get update
  - sudo wget https://dl.google.com/go/go1.9.4.linux-ppc64le.tar.gz
  - sudo tar -C /usr/local -xzf go1.9.4.linux-ppc64le.tar.gz
  - export PATH=$PATH:/usr/local/go/bin

install:
  - yarn install --pure-lockfile
  - cd $GOPATH
  - mkdir src
  - cd src
  - mkdir github.com
  - cd github.com
  - mkdir grafana
  - cd grafana
  - go get github.com/grafana/grafana
  - cd $GOPATH/src/github.com/grafana/grafana
  - go run build.go setup
  - go run build.go build
  - yarn install --pure-lockfile
script:
- yarn test
