dist: trusty
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.11.5"

install:
  - cd $GOPATH/src
  - mkdir github.com
  - cd github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git 
  - cd grafana
  - go run build.go setup
  - go run build.go build

script:
- yarn test
