dist: bionic
os: linux
arch: ppc64le
sudo: required
language: go
go:
- "1.14.4"

install:
  - cd /bin
  - sudo wget https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs
  - sudo chmod 777 phantomjs
  - sudo apt update
  - nvm install 12.13.1
  - npm install -g yarn
script:
  - cd $GOPATH/src/github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git
  - cd grafana
  - make
  - make test
  
notifications:
  slack:
    rooms:
      - secure: "m/SzD+ZVyv8k4AybZYIxqUAgfDWu5bkTIVJqJpwl4lkPHll1x9f+7tqpN0B4Pn+Y1KLIxyLLOYAP6wspiMV7KOhCkReBF2X1vVCYG6giygm6uJOf/qPv0ynCCKcGf+kU+e/pFtT+RpNbZ3/ReuZV7Xj0s6BfAjYKpZimK2ZsKp0Cd4Oxz25a+4JVk32FfSRpazwPAXEcPZRiOnz7ZymimtWsA3A7V67cKIqxXyd8lYX/knn5TJAKOtWycsKiC9z8vHZ7mPf5HQYDkZEyYB3MdjPUHRHMNyrNdyCYcReevdJU6FUBiE8yRuDBxerIUIOuDfF8HH9hVdDHzkKlC6i6nth3UPQMfwNaUIPGte2j4JDW4hgho9PxoySWFksjF2ok6ofEwj9d4sNYOQdVcofJxYbcc3S7gLwNbP35058cg6vYLkx+j6+K6E37gAaIO0Ei8qd8+BaRxbr3XqkMMdhBKHysHLWg2mNbQQTNz6GAy9K589GhOP8djGBF80wIEH2jMVa8k3d5OoKOb8jZ0GHFGQ6bKLLvjTwkB+MKLaG+GSnrPq6hB/8YcLZGy/a7GXeVyrX8wQWQu1wj5EH6mcQbaQUfdaNId2OpFg/nA5aZa8YWbkCSe6kWoOxmmwMyHsmNnMCqtpWZF7na6GdAtdK6xICUXC/xIhCRgDO39IWkLFs="
    on_success: change
    on_failure: always
