dist: xenial
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.11.5"

before_install:
  - cd /bin
  - sudo wget https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs
  - sudo chmod 777 phantomjs
  - sudo apt-get update
  - nvm install 8

install:
  - cd $GOPATH/src/github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git 
  - cd grafana
  - go run build.go setup
  - go run build.go build
  - yarn install --pure-lockfile
script:
- yarn test
