dist: xenial
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.11.5"

install:
  - touch /etc/apt/sources.list.d/nodesource.list
  - echo "    6.2.1-1nodesource1~xenial1 500" > /etc/apt/sources.list.d/nodesource.list
  - echo "       500 https://deb.nodesource.com/node_6.x xenial/main amd64 Packages" > /etc/apt/sources.list.d/nodesource.list
  - echo "    4.2.6~dfsg-1ubuntu4 500" > /etc/apt/sources.list.d/nodesource.list
  - echo "       500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages" > /etc/apt/sources.list.d/nodesource.list
  - curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - yarn install --pure-lockfile
  - cd $GOPATH/src/github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git 
  - cd grafana
  - go run build.go setup
  - go run build.go build

script:
- yarn test
