dist: xenial
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.11.5"

before_install:
  - sudo apt-get update
  - nvm install 8

install:
  - yarn install --pure-lockfile
  - cd $GOPATH/src/github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git 
  - cd grafana
  - go run build.go setup
  - go run build.go build
  - yarn install --pure-lockfile
script:
- yarn test
