dist: trusty
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.11.5"

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - yarn install --pure-lockfile
  - cd $GOPATH/src/github.com
  - mkdir grafana
  - cd grafana
  - git clone https://github.com/grafana/grafana.git 
  - cd grafana
  - go run build.go setup
  - go run build.go build

script:
- yarn test
